### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [prosaicpoet123/prj-rev-bwfs-dasmoto#3]
Excellent, So when I review this project I look for two things, use of divs and no repetition of css.

Divs are by nature design to divide each section of your web page into manageable containers.
So in the beginning some do not realize why they should use them.  I always mention this because as you progress through the program you will see that you will put everything into a div.

Your css was excellent, my assumption is you forgot to remove those two sections.  It look like your goal was to reduce how much you repeated yourself.

After you divide your sections into divs, take a look at bootstrap.  See if you can add it to this site to make it mobile friendly.  It will also heavily reinforce the concept of using divs.

**Comment by prosaicpoet123** [comment]
Thanks for the feedback farish. In truth, I originally had the divs on the page, but remove them to make it more "lightweight" so to speak. Normally I am in the habit of using divs to group my content together, but I will keep this in mind going forward.

The CSS was a mistake. I remove the "bold" class from the document but forgot to remove the markup in the CSS file. Need to be more vigilant :o)
